"use server";

import { db } from "@/lib/db";
import { resources, users } from "@/lib/db/schema";

import { auth } from "@/lib/auth";
import { z } from "zod";
import { revalidatePath, revalidateTag } from "next/cache";
import { eq, desc, ilike, and, isNull, sql } from "drizzle-orm";
import { deleteR2Object } from "@/lib/r2";
import { escapeLike } from "@/lib/utils";
import { ALLOWED_FILE_TYPES, MAX_FILE_SIZE } from "@/lib/uploads";
import {
  isDriveLink,
  isEditableDocsLink,
  parseDriveLink,
  checkDriveLinkProblem,
  driveDirectDownloadUrl,
  driveMetaFromResponse,
  resolveDriveFileType,
  DRIVE_FILE_TYPE,
} from "@/lib/drive";
import { checkRateLimit } from "./rate-limit";
import { runAsUser } from "@/lib/db/scoped";

// True once the database has the upload_key column (drizzle/0008). Checked
// lazily and cached per server process: one information_schema probe per
// cold start, then free. Lets a code deploy ship before the migration runs
// without 42703-ing every upload — the action degrades to the legacy insert.
let uploadKeyColumnKnown: boolean | null = null;
async function uploadKeyColumnAvailable(): Promise<boolean> {
  if (uploadKeyColumnKnown !== null) return uploadKeyColumnKnown;
  try {
    const result = await db.execute(sql`
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'resources'
        and column_name = 'upload_key'
      limit 1
    `);
    uploadKeyColumnKnown = result.rows.length > 0;
  } catch (error) {
    console.error("upload_key column probe failed; assuming not migrated:", error);
    uploadKeyColumnKnown = false;
  }
  return uploadKeyColumnKnown;
}

const resourceSchema = z.object({
  title: z.string().min(3).max(100),
  description: z.string().max(500).optional(),
  type: z.enum(["assignment", "quiz", "past-paper", "notes", "other"]),
  subject: z.string().min(2).max(50),
  professor: z.string().max(50).optional(),
  department: z.string().max(50).optional(),
  // R2-hosted resources carry the public URL + object key. Drive-hosted
  // resources ("source: drive") carry the share URL in file_url and the
  // Drive file id in file_key — the download route branches on that shape.
  file_url: z.string().url(),
  file_key: z.string().min(1).max(500),
  // R2 uploads must be one of the allowed MIME types. Drive resources carry
  // the synthetic DRIVE_FILE_TYPE marker instead — validated by branch below.
  file_type: z.string().min(3).max(120),
  // Drive resources have no 4 MB platform cap (bytes never cross the
  // server), so the size check is source-dependent — see uploadResource.
  file_size: z.number().min(1).max(MAX_FILE_SIZE).optional(),
  // Idempotency: one stable UUID per logical upload, generated by the client
  // before the file PUT and reused for the resource insert. A retry after a
  // lost response (flaky network, function timeout) then dedupes instead of
  // creating a second copy of the resource.
  uploadId: z.string().uuid().optional(),
  // "r2" (default — plain file upload) or "drive" (Google Drive share link).
  source: z.enum(["r2", "drive"]).optional(),
});

export async function uploadResource(formData: {
  title: string;
  description?: string;
  type: string;
  subject: string;
  professor?: string;
  department?: string;
  file_url: string;
  file_key: string;
  file_type: string;
  file_size?: number;
  uploadId?: string;
  source?: "r2" | "drive";
}) {
  const session = await auth();
  const uploaderEmail = session?.user?.email;
  if (!session?.user || !uploaderEmail) {
    throw new Error("Authentication required");
  }

  // Verified email required to upload: unverified users can sign in and
  // browse (nagged by the banner), but can't contribute content until they
  // prove ownership of their address.
  const [uploader] = await db
    .select({ emailVerified: users.emailVerified })
    .from(users)
    .where(eq(users.email, uploaderEmail));
  if (!uploader?.emailVerified) {
    throw new Error(
      "Verify your email address before uploading — check your inbox for the verification link, or use 'Resend verification email' at the top of the page."
    );
  }

  // Rate limit uploads per user (10/hour) — storage is the expensive,
  // abusable resource here.
  if (!(await checkRateLimit(`upload:${session.user.id}`, 10, 3600))) {
    throw new Error("Upload limit reached for this hour. Please try again later.");
  }

  const validatedData = resourceSchema.parse(formData);
  const uploadKey = validatedData.uploadId ?? null;

  /* ---- Drive-hosted resources: verify the link before saving it. ----
     A share link that isn't actually "Anyone with the link" downloads
     fine for the owner and breaks for every student forever. The probe
     runs here (server-side) as the authoritative gate — the form's live
     check is UX, this is the guarantee. fileKey stores the Drive file id
     (the download route rebuilds the direct-download URL from it) and
     fileUrl keeps the human-meaningful share link the uploader pasted. */
  if (validatedData.source === "drive") {
    if (!isDriveLink(validatedData.file_url)) {
      throw new Error("That doesn't look like a Google Drive link.");
    }
    if (isEditableDocsLink(validatedData.file_url)) {
      throw new Error(
        "Google Docs/Sheets/Slides links can't be downloaded. In Docs, use File → Download → PDF and share the PDF file instead."
      );
    }
    const parsed = parseDriveLink(validatedData.file_url);
    if (!parsed) {
      throw new Error(
        "Couldn't find a file id in that link — copy the share link from Drive's “Share → Copy link”."
      );
    }
    const problem = await checkDriveLinkProblem(parsed.fileId);
    if (problem) throw new Error(problem);
    // Trust the probed id over the raw URL (handles open?id= variants etc.).
    validatedData.file_key = parsed.fileId;
    validatedData.file_url = driveDirectDownloadUrl(parsed.fileId);

    // Harvest metadata from a second 1-byte probe (the check above validates;
    // this reads the headers). The MIME/extension decides the stored
    // file_type — a real PDF/ZIP/video label on cards instead of a generic
    // DRIVE chip. The server decides; the client's claim is ignored, so a
    // tampered payload can't smuggle an arbitrary file_type in. If the
    // harvest fails, fall back to the client-probed type (also derived from
    // Drive's response, just moments earlier) then to the synthetic marker.
    let harvested: { mimeType: string | null; fileName: string | null } | null = null;
    try {
      const metaRes = await fetch(driveDirectDownloadUrl(parsed.fileId), {
        method: "GET",
        redirect: "follow",
        headers: { Range: "bytes=0-0" },
      });
      const meta = driveMetaFromResponse(metaRes);
      harvested = { mimeType: meta.mimeType, fileName: meta.fileName };
      // Size from the harvest too, when the client didn't send one.
      if ((!validatedData.file_size || validatedData.file_size <= 0) && meta.fileSize) {
        validatedData.file_size = meta.fileSize;
      }
    } catch {
      // Metadata is optional — validation already passed above.
    }
    validatedData.file_type =
      resolveDriveFileType(harvested?.mimeType ?? null, harvested?.fileName ?? null) ??
      (validatedData.file_type === DRIVE_FILE_TYPE ||
       ALLOWED_FILE_TYPES.has(validatedData.file_type)
        ? validatedData.file_type // probe-agreed client claim
        : DRIVE_FILE_TYPE); // unknown — generic label
    if (!validatedData.file_size || validatedData.file_size <= 0) {
      validatedData.file_size = undefined;
    }
  } else {
    // R2 path: the original allow-list gate (marker type must never ride
    // the upload path, and upload MIME types must be real).
    if (!ALLOWED_FILE_TYPES.has(validatedData.file_type)) {
      throw new Error("File type not allowed");
    }
    if (!validatedData.file_size || validatedData.file_size <= 0) {
      throw new Error("File size is required for uploaded files");
    }
  }

  // Legacy deploy fallback: if the upload_key migration hasn't been applied
  // yet (code deploys can land before `npm run db:migrate` does), the keyed
  // SQL would 42703 on the missing column. Probe once, remember the answer
  // for the process lifetime, then behave exactly as before the fix — a
  // plain insert — instead of failing every upload.
  const hasUploadKeyColumn = await uploadKeyColumnAvailable();

  // Idempotent insert: retries with the same uploadId find the row the first
  // attempt already wrote and reuse it instead of creating a duplicate. The
  // pre-check is best-effort (races fall through to the unique index); both
  // lookups are scoped to this user, so a key can never adopt someone
  // else's resource or leak its id.
  if (uploadKey && hasUploadKeyColumn) {
    const existing = await db.query.resources.findFirst({
      where: and(eq(resources.uploadKey, uploadKey), eq(resources.uploaderId, session.user.id)),
    });
    if (existing) {
      return { id: existing.id, alreadyExisted: true };
    }
  }

  // RLS-scoped insert: the database itself rejects a row whose uploader_id
  // isn't the verified session user, even if the code path regresses.
  // ON CONFLICT DO NOTHING (not DO UPDATE) keeps this INSERT-only — app_rls
  // has no UPDATE policy by design. When a concurrent first attempt wins the
  // unique-key race, the empty RETURNING is resolved by the select below.
  const results = await runAsUser(
    session.user.id,
    hasUploadKeyColumn
      ? (sql) => [
          sql`insert into resources (title, description, type, subject, professor, department, file_url, file_key, file_type, file_size, uploader_id, upload_key)
              values (${validatedData.title}, ${validatedData.description ?? null}, ${validatedData.type}, ${validatedData.subject},
                      ${validatedData.professor ?? null}, ${validatedData.department ?? null}, ${validatedData.file_url},
                      ${validatedData.file_key}, ${validatedData.file_type}, ${validatedData.file_size ?? null}, ${session.user.id}, ${uploadKey})
              on conflict (upload_key) do nothing
              returning id`,
        ]
      : // Column not migrated yet — plain insert (no idempotency, no dupes created).
        (sql) => [
          sql`insert into resources (title, description, type, subject, professor, department, file_url, file_key, file_type, file_size, uploader_id)
              values (${validatedData.title}, ${validatedData.description ?? null}, ${validatedData.type}, ${validatedData.subject},
                      ${validatedData.professor ?? null}, ${validatedData.department ?? null}, ${validatedData.file_url},
                      ${validatedData.file_key}, ${validatedData.file_type}, ${validatedData.file_size ?? null}, ${session.user.id})
              returning id`,
        ]
  );
  // Batch results: [role-switch rows, identity rows, insert rows].
  // Empty insert rows = a concurrent attempt with the same uploadId already
  // committed this user's upload — return that row instead of failing.
  const insertRows = results[2] as { id: string }[] | undefined;
  let created = insertRows?.[0];
  let alreadyExisted = false;
  if (!created && uploadKey && hasUploadKeyColumn) {
    const existing = await db.query.resources.findFirst({
      where: and(eq(resources.uploadKey, uploadKey), eq(resources.uploaderId, session.user.id)),
    });
    if (existing) {
      created = existing;
      alreadyExisted = true;
    }
  }

  revalidatePath("/");
  revalidatePath("/browse");
  revalidateTag("recent-resources", "default");
  return { id: created?.id, alreadyExisted };
}

export async function deleteResource(resourceId: string) {
  const parsed = z.string().uuid().safeParse(resourceId);
  if (!parsed.success) throw new Error("Invalid resource id");

  const session = await auth();
  if (!session?.user) {
    throw new Error("Authentication required");
  }

  const resource = await db.query.resources.findFirst({
    where: eq(resources.id, parsed.data),
  });

  if (!resource) {
    throw new Error("Resource not found");
  }

  if (resource.uploaderId !== session.user.id) {
    throw new Error("Unauthorized to delete this resource");
  }

  // Delete from R2 — Drive-hosted resources have no stored object; their
  // fileKey is a Drive file id and R2 must not try to delete a key that
  // never existed. isDriveLink on the stored URL is the marker.
  if (resource.fileKey && !isDriveLink(resource.fileUrl)) {
    await deleteR2Object(resource.fileKey);
  }

  // Delete from DB
  await db.delete(resources).where(eq(resources.id, parsed.data));

  revalidatePath("/");
  revalidatePath("/browse");
  revalidateTag("recent-resources", "default");
}

export async function checkDuplicateResources(
  title: string,
  subject: string,
  department?: string
) {
  try {
    // Guest-reachable and fired on every title keystroke debounce — rate
    // limit per user (or IP for the pre-login flow) to blunt scraping.
    const session = await auth();
    const key = session?.user?.id ?? "guest";
    if (!(await checkRateLimit(`dupcheck:${key}`, 30, 60))) return [];

    // A same-title resource only counts as a duplicate when it belongs to the
    // SAME department (compared case-insensitively). A different department
    // means it is that department's own material — a genuinely new resource.
    // Both sides missing a department counts as the same; a department on one
    // side only counts as different.
    const normalizedDepartment = department?.trim().toLowerCase() || null;
    const departmentFilter = normalizedDepartment
      ? sql`lower(${resources.department}) = ${normalizedDepartment}`
      : isNull(resources.department);

    const duplicates = await db
      .select({
        id: resources.id,
        title: resources.title,
        subject: resources.subject,
        type: resources.type,
        department: resources.department,
        createdAt: resources.createdAt,
        uploader: { name: users.name },
      })
      .from(resources)
      .leftJoin(users, eq(resources.uploaderId, users.id))
      .where(
        and(
          ilike(resources.title, `%${escapeLike(title)}%`),
          eq(resources.subject, subject),
          departmentFilter
        )
      )
      .orderBy(desc(resources.createdAt))
      .limit(5);

    return duplicates;
  } catch (error) {
    console.error("Failed to check duplicates:", error);
    return [];
  }
}
